version: '3'

services:
    home-server:
        image: home-server:latest
        restart: always
        volumes:
            - /home/rasmus/.config/gohome.yaml:/.config/gohome.yaml
        ports:
            - 50051:50051
