// Code generated by protoc-gen-go. DO NOT EDIT.
// source: home.proto

package home

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RunActionRequest struct {
	Room                 string   `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	Lamp                 string   `protobuf:"bytes,2,opt,name=lamp,proto3" json:"lamp,omitempty"`
	Action               string   `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	Value                string   `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunActionRequest) Reset()         { *m = RunActionRequest{} }
func (m *RunActionRequest) String() string { return proto.CompactTextString(m) }
func (*RunActionRequest) ProtoMessage()    {}
func (*RunActionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_711cc65aaf7510e9, []int{0}
}

func (m *RunActionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunActionRequest.Unmarshal(m, b)
}
func (m *RunActionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunActionRequest.Marshal(b, m, deterministic)
}
func (m *RunActionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunActionRequest.Merge(m, src)
}
func (m *RunActionRequest) XXX_Size() int {
	return xxx_messageInfo_RunActionRequest.Size(m)
}
func (m *RunActionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RunActionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RunActionRequest proto.InternalMessageInfo

func (m *RunActionRequest) GetRoom() string {
	if m != nil {
		return m.Room
	}
	return ""
}

func (m *RunActionRequest) GetLamp() string {
	if m != nil {
		return m.Lamp
	}
	return ""
}

func (m *RunActionRequest) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *RunActionRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type RunActionResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunActionResponse) Reset()         { *m = RunActionResponse{} }
func (m *RunActionResponse) String() string { return proto.CompactTextString(m) }
func (*RunActionResponse) ProtoMessage()    {}
func (*RunActionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_711cc65aaf7510e9, []int{1}
}

func (m *RunActionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunActionResponse.Unmarshal(m, b)
}
func (m *RunActionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunActionResponse.Marshal(b, m, deterministic)
}
func (m *RunActionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunActionResponse.Merge(m, src)
}
func (m *RunActionResponse) XXX_Size() int {
	return xxx_messageInfo_RunActionResponse.Size(m)
}
func (m *RunActionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RunActionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RunActionResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*RunActionRequest)(nil), "RunActionRequest")
	proto.RegisterType((*RunActionResponse)(nil), "RunActionResponse")
}

func init() { proto.RegisterFile("home.proto", fileDescriptor_711cc65aaf7510e9) }

var fileDescriptor_711cc65aaf7510e9 = []byte{
	// 163 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0xc8, 0xcf, 0x4d,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xca, 0xe0, 0x12, 0x08, 0x2a, 0xcd, 0x73, 0x4c, 0x2e,
	0xc9, 0xcc, 0xcf, 0x0b, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe2, 0x62, 0x29, 0xca,
	0xcf, 0xcf, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x41, 0x62, 0x39, 0x89, 0xb9,
	0x05, 0x12, 0x4c, 0x10, 0x31, 0x10, 0x5b, 0x48, 0x8c, 0x8b, 0x2d, 0x11, 0xac, 0x51, 0x82, 0x19,
	0x2c, 0x0a, 0xe5, 0x09, 0x89, 0x70, 0xb1, 0x96, 0x25, 0xe6, 0x94, 0xa6, 0x4a, 0xb0, 0x80, 0x85,
	0x21, 0x1c, 0x25, 0x61, 0x2e, 0x41, 0x24, 0x9b, 0x8a, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x8d, 0x9c,
	0xb9, 0xb8, 0x3d, 0xf2, 0x73, 0x53, 0x83, 0x53, 0x8b, 0xca, 0x32, 0x93, 0x53, 0x85, 0x4c, 0xb8,
	0x38, 0xe1, 0x6a, 0x84, 0x04, 0xf5, 0xd0, 0x5d, 0x26, 0x25, 0xa4, 0x87, 0x61, 0x84, 0x12, 0x43,
	0x12, 0x1b, 0xd8, 0x2b, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa7, 0x6a, 0x2b, 0x01, 0xd8,
	0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HomeServiceClient is the client API for HomeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HomeServiceClient interface {
	RunAction(ctx context.Context, in *RunActionRequest, opts ...grpc.CallOption) (*RunActionResponse, error)
}

type homeServiceClient struct {
	cc *grpc.ClientConn
}

func NewHomeServiceClient(cc *grpc.ClientConn) HomeServiceClient {
	return &homeServiceClient{cc}
}

func (c *homeServiceClient) RunAction(ctx context.Context, in *RunActionRequest, opts ...grpc.CallOption) (*RunActionResponse, error) {
	out := new(RunActionResponse)
	err := c.cc.Invoke(ctx, "/HomeService/RunAction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HomeServiceServer is the server API for HomeService service.
type HomeServiceServer interface {
	RunAction(context.Context, *RunActionRequest) (*RunActionResponse, error)
}

// UnimplementedHomeServiceServer can be embedded to have forward compatible implementations.
type UnimplementedHomeServiceServer struct {
}

func (*UnimplementedHomeServiceServer) RunAction(ctx context.Context, req *RunActionRequest) (*RunActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunAction not implemented")
}

func RegisterHomeServiceServer(s *grpc.Server, srv HomeServiceServer) {
	s.RegisterService(&_HomeService_serviceDesc, srv)
}

func _HomeService_RunAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HomeServiceServer).RunAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/HomeService/RunAction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HomeServiceServer).RunAction(ctx, req.(*RunActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HomeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "HomeService",
	HandlerType: (*HomeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunAction",
			Handler:    _HomeService_RunAction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "home.proto",
}
